disabled_rules:
  - trailing_comma
  - nesting
  - fallthrough
  - shorthand_operator
  - todo
  - large_tuple
  - identifier_name
  - type_name
  - type_body_length
  # TODO: Why is vertical_parameter_alignment giving false positives?
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  # TODO: Enable when removing support for older Swift versions (<5.6)
  - unavailable_condition
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - literal_expression_end_indentation
  - overridden_super_call
  - prohibited_super_call
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - nslocalizedstring_key
  - unused_setter_value
custom_rules:
  comment_whitespace:
    name: "Comment Whitespace"
    regex: //\S
    match_kinds: comment
    message: "Comments must begin with a whitespace character"
  spaces_not_tabs:
    name: "Tabs not Spaces"
    regex: ^( )
    message: "Use tabs instead of spaces"
  point_zero:
    name: "Point Zero"
    regex: '(?<!iOS\s)(?<!macOS\s)(?<!\.)\b[\d_]+\.0\b'
    match_kinds:
      - number
      - attribute.builtin
    message: "Don't add a .0 to the end of floating point literals"
  color_init:
    name: "Color Initializer"
    regex: 'UIColor\(red: (.+), green: \1, blue: \1, alpha: .+\)'
    message: "Use UIColor(white:alpha:)"
force_try: warning
force_cast: warning
function_body_length: 200
line_length: 200
file_length: 450
cyclomatic_complexity: 12
function_parameter_count: 7
